### ISSUE TITLE
Descriptor doesn't have an initializer method

### ISSUE THREAD

**Issue by buzinas** [Riim/cellx#1]
Probably you're using Babel to transpile your code, and that's why you're using `var value = descr.initializer();`, but it won't work with other transpilers (such as TypeScript), nor with vanilla ES6.

Couldn't you be using `descr.value` directly?

**Comment by Riim** [comment]
Initializer method is not a feature of babel, it is a part of proposed standard: [INITIALIZER_INTEROP](https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md).

Implementation of descriptors in TypeScript is not full and probably it will soon be complemented by initializer: [TypeScript/issues/4736](https://github.com/Microsoft/TypeScript/issues/4736).

**Comment by buzinas** [comment]
@Riim thanks, you can close this issue. Sorry :)
