### ISSUE TITLE
Почему такой сложный nextTick?

### ISSUE THREAD

**Issue by arvitaly** [Riim/cellx#12]
https://github.com/Riim/cellx/blob/master/src/Utils/nextTick.js
Почему именно nextTick и полифиллы, а не обычный setTImeout, 0?

Просто не очень люблю асинхронное тестирование, ну и интересна настоящая причина?
Обычно `jasmine.clock().install()` спасает от callback-hell...

**Comment by arvitaly** [comment]
Или, может быть, придумать альтернативный синхронный способ для запуска всех отложенных расчетов?
Типа, `cellx.next()`?

Или, возможность замены, типа `cellx.Utils.nextTick=(cb)=>cb()`

**Comment by Riim** [comment]
> Почему именно nextTick и полифиллы, а не обычный setTImeout, 0?

быстрее: [1](https://habrahabr.ru/post/275023/), [2](http://jphpsf.github.io/setImmediate-shim-demo/).

> для запуска всех отложенных расчетов?

при обычной работе расчёты [запускаются синхронно](https://github.com/Riim/cellx/blob/c3982069d7ac71ecd24fb77fcc20f4d8cac13f6d/src/Cell.js#L636-L638) когда это необходимо:

``` js
let a = cellx(1);
let b = cellx(function() { return a() + 1; });
a(2);

// при чтении `b` cellx поймёт, что что-то поменялось
// и возможно эти изменения влияют на результат `b`
// и запустит расчёты изменений синхронно
console.log(b());
// => 3
```

Раньше ещё был [Cell.forceRelease](https://github.com/Riim/cellx/blob/785aecd6b9befc17d1b6c5d2fa4c54243f87dec5/src/Cell.js#L195), но он как-то нигде не пригодился, разве что в тестах его использовать.

**Comment by arvitaly** [comment]
Беда не с ячейками. а с подписчиками

``` javascript
var cellx = require('cells');
var a = cellx(), test;
cellx("subscribe", () => {
    test = a();    
});
a(1);
console.assert(test === 1);

```

А в тестах это превращается в ужас:

``` javascript
var cellx = require('cellx');
var a = cellx(), test;
a("subscribe", () => {
    test = a();
});
a(1);
setTimeout(() => {
    console.assert(test === 1);
    a(2);
    setTimeout(() => {
        console.assert(test === 2);
    }, 1)
}, 1)
```

forceRelease не нашелся в `cellx.Cell` или как к нему добраться, и он только для одной ячейки или для всех?

**Comment by arvitaly** [comment]
Пока выкрутился так

``` javascript
process.nextTick = function (cb) {
    cb.apply(undefined, Array.prototype.slice.call(arguments, 1))
}
```

Но не очень нравится)

**Comment by Riim** [comment]
Вернул `Cell.forceRelease()`, v1.6.43

> он только для одной ячейки или для всех?

для всех.

**Comment by arvitaly** [comment]
Да, супер, уже big thanks, работает! В идеале бы еще, возможность подписку делать синхронной.

**Comment by Riim** [comment]
Она и так синхронная))

**Comment by arvitaly** [comment]
В смысле, вызов listener'ов. Ну чтобы вот это работало в тестах:

``` javascript
var cellx = require('cellx');
var a = cellx(), test;
a("subscribe", () => {
    test = a();
});
a(1);
console.assert(test === 1);
a(2);
console.assert(test === 2);
```

Иногда нужно вручную вызов callback контролировать, тут forceRelease поможет, а иногда просто, чтобы вызывалось синхронно, тут forceRelease после каждого изменения писать - overhead.

**Comment by Riim** [comment]
Одновременно сохранить [схлопывание событий](https://github.com/Riim/cellx/blob/master/README.ru.md#Схлопывание-и-отбрасывание-событий) и сделать cellx синхронным никак не получится, но если первое для тестов не важно, то, наверно, переопределять nextTick не так уж и плохо. Главное случайно не сделать так в рабочем приложении))

**Comment by arvitaly** [comment]
Ну вот если бы переопределять не в process.nextTick, а вынести наружу nextTick, который в cellx (типа cellx._nextTick = ()=>...), было бы совсем круто. А то некоторые инструменты тестирования сами используют nextTick и возникают коллизии.

**Comment by Riim** [comment]
v1.6.44
можно переопределять так:

``` js
cellx.Cell._nextTick = () => {/* ... */};
```

**Comment by arvitaly** [comment]
It works! Impressive! Спасибо!

**Comment by Riim** [comment]
В `1.6.60` появился [синхронный режим работы](https://github.com/Riim/cellx/issues/15). Если не против, я попозже уберу `Cell._nextTick`?
