### ISSUE TITLE
Опциональная асинхронность и транзакции

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#15]
Сейчас все обновления делаются асинхронно, на следующем тике. 
Добавьте пожалуйста настройку для смены такого поведения на синхронное и метод для транзакции по аналогии с mobx.transaction. Есть много причин, почему такое поведение бывает удобнее, например, отладка и обработка ошибок.

Я делаю atom overlay https://github.com/zerkalica/atmover, который является абстракцией над разными реализациями атомов и сейчас для cellx transaction реализован так:

```js
function transact(f: () => void): void {
            f()
            cellx.Cell.forceRelease()
}
```

Вроде cellx.Cell.forceRelease не описан в api, следовательно может поменяться поведение.

**Comment by Riim** [comment]
Привет, в `1.6.58` добавил `cellx.transact`.
Мне кажется, что `mobx.transaction` немного неправильно работает:

``` js
let num = mobx.observable(1);
let num2 = mobx.observable(2);

try {
    mobx.transaction(() => {
        num.set(2);
        num.set(3);
        num2.set(5);
        throw 1;
        num2.set(10);
    });
} catch (err) {}

console.log('num: ' + num.get());
// => "num: 2"
console.log('num2: ' + num2.get());
// => "num2: 5"
```

Из википедии:

> Транза́кция — минимальная логически осмысленная операция, которая имеет смысл и может быть совершена только полностью.

То есть mobx должен откатить изменения из-за ошибки и последние два console.log-а должны вывести "num: 1" и "num2: 2".

У меня вроде получились правильные транзакции:

``` js
let num = cellx(1);
let num2 = cellx(2);

cellx.transact(() => {
    num(2);
    num(3);
    num2(5);
    throw 1;
    num2(10);
});

console.log('num: ' + num());
// => num: 1
console.log('num2: ' + num2());
// => num2: 2
```

> отладка

порядок вычисления в синхронном режиме может заметно измениться и такая отладка скорее оставит ещё больше вопросов.

> обработка ошибок

это актуально для mobx который падает при ошибке в формуле, cellx в этом случае создаёт на ячейке событие `error`, оно же распространяется по всем вычисляемым ячейкам. Единственный способ добиться падения -- [запись в невычисляемую ячейку](https://github.com/Riim/cellx/blob/master/README.ru.md#validate), но тут и до вычисления просто не доходит. В общем, совсем другой подход к обработке ошибок.

Если всё равно очень нужно, то можно включать костылём вроде такого (не проверял):

``` js
let originalSet = cellx.Cell.prototype.set;
cellx.Cell.prototype.set = function() {
    originalSet.apply(this, arguments);
    cellx.Cell.forceRelease();
};
```

но добавлять это в библиотеку как-то не хочется, так как костылище)).

**Comment by zerkalica** [comment]
Спасибо.

> порядок вычисления в синхронном режиме может заметно измениться и такая отладка скорее оставит ещё больше вопросов.

Не очень понимаю о чем речь, пример можно?

**Comment by Riim** [comment]
http://jsbin.com/cudevigobe/edit?js,console
асинхронно: "c", "d"
синхронно: "d", "c", "d".

**Comment by zerkalica** [comment]
Несколько set нужно делать только внутри транзакции. Транзакции через таймеры, которые сейчас, хоть и просто, но это магия, некое соглашение, поведение которого нельзя изменить. В коде лучше явно сказать, что эти апдейты внутри транзакции, чем держать в голове, что они выполнятся в следующем тике.

Как быть с известной реактовой багой, когда курсор перескакивает в начало инпута, если  стейт обновился асинхронно. Скорее forceRelease (как и любой другой force*) выглядит костылем, чем синхронное обновление+транзакции.

По поводу обработки ошибок: http://jsbin.com/kesiperese/1/edit?js,console
Если откомментарить // cellx.Cell.forceRelease();, то виден весь путь до ошибки, а без него, только до cellx.

В [баобабе](https://github.com/Yomguithereal/baobab), например, тоже изначально только через таймеры были транзакции, потом автор добавил параметр asynchronous, по-умолчанию он true, но скорее всего это из-за совместимости с легаси.

**Comment by Riim** [comment]
В `1.6.60` синхронный режим можно включить так:

``` js
cellx.configure({ asynchronous: false });
```

**Comment by zerkalica** [comment]
Спасибо, работает.

Баг только обнаружил:

``` js
let a = cellx(1);
cellx.configure({ asynchronous: false });

function fn(err, evt) {
    console.log(evt.value)
}

console.log('start')

var o = {a: a}
o.a('subscribe', fn)
a(2) // ничего не выведет
```

cellx считает o.a() и a() как разные ячейки

http://jsbin.com/hobikigeju/edit?js,console

**Comment by Riim** [comment]
Это фича)) Значение ячейки привязано к контексту в котором она запускается, это необходимо для возможности объявления ячеек в прототипе:

``` js
function User() {}
User.prototype.name = cellx();

var user1 = new User();
var user2 = new User();

user1.name('Матроскин');
user2.name('Шарик');

console.log(user1.name());
// => "Матроскин"
```

Без этой фичи `user1.name()` вдруг станет Шариком.
Если это не нужно, можно использовать внутренний класс `cellx.Cell`, сам `cellx` -- это просто обёртка над ним, реализующая всякие такие странности с контекстом.

``` js
function User() {}
User.prototype.name = new cellx.Cell();

var user1 = new User();
var user2 = new User();

user1.name.set('Матроскин');
user2.name.set('Шарик');

console.log(user1.name.get());
// => "Шарик"
```

**Comment by zerkalica** [comment]
Ок, не совсем очевидно как-то. Действительно так нужны эти упрощения в виде одной god-функции в ущерб явности? Может хотя бы какой-нить cellx.prop сделать ?

В mobx более логично выглядит extendsObservable(this, {bla-bla}), да, в конструкторе, но код понятнее получается.

На мой взгляд, проблема на стыке атомов и обычного кода, в mobx magic get/set, в cellx свойства похожиме на get/set методы. Из-за этого куча извратов городить приходится.

Например, в погоне за похожестью на привычный многим код, без оберток над данными, у тебя используется антипаттерн строковая типизация. Например, a('subscribe', fn) - по сути вызов метода a.subscribe(fn)

Если взять flow или typescript и по-честному, без any, переписать тип [ICellx](https://github.com/Riim/cellx/blob/master/src/cellx.d.ts), то ни typescript, ни flow его не переварят, т.к. там нет паттерн-матчинга по сигнатуре функции.

Может конечно не так что-то делаю, вот пример на typescript:

``` ts
type CellxEvent<V> = {
    type: 'change';
    oldValue?: V;
    value: V;
}
type ListenerName = 'addChangeListener' | 'removeChangeListener'
type CellxListener<V> = (eventName: ListenerName, fn: (event: CellxEvent<V>) => void) => void
type CellxSet<V> = (v: V) => void
type CellxGet<V> = () => V

type CellxAtom<V> = CellxListener<V> | CellxSet<V> | CellxGet<V>

type Cellx<V> = () => CellxAtom<V>

var f: any = 0
var fn: Cellx<number> = f

var a: CellxAtom<number> = fn()
var val: number = a() // Can not invoke an expression ...
```

По мне, идея atom-подобных оберток внутри обычного кода - костыль. Нужно наоборот, при помощи [инверсии контроля](https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)
выполнять обычный код внутри атомов, т.е. [di](https://ru.wikipedia.org/wiki/%D0%92%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8)-контейнер управляет не только созданием объектов, но и их реактивностью, вынося за сцену все эти get/set, computable, observable, action.

**Comment by Riim** [comment]
> так нужны эти упрощения в виде одной god-функции в ущерб явности

современные js-движки развращают своей скоростью, раньше создавать методы в конструкторе было страшным грехом, а сейчас пожалуйста, сколько хочешь. Объявление ячейки в прототипе позволяет не создавать функцию на каждое свойство каждого экземпляра, плюс экземпляры `cellx.Cell` создаются при этом лениво, при первом обращении к свойству. Это лучшее сочетание скорости и удобства.
Если же скорость и потребление памяти не особо важны, то есть `cellx.define`:

``` js
function User(name) {
    cellx.define(this, { name: name });
}

var user1 = new User();
var user2 = new User();

user1.name = 'Матроскин';
user2.name = 'Шарик';

console.log(user1.name);
// => "Матроскин"
```

Ещё более современный вариант: [cellx-decorators](https://github.com/Riim/cellx-decorators#cellx-decorators).

Про странный синтаксис вызова методов рассказывал здесь: https://github.com/Riim/cellx/issues/8 . К написанному там можно добавить, что с новым, уже описанным в стандарте `__proto__`, подставить свой прототип функции всё же можно (IE11+):

``` js
function f() {}
f.__proto__ = { __proto__: Function.prototype, myProp: 1 };

console.log(f.call);
// => function call() { [native code] }
console.log(f.myProp);
// => 1
```

То есть при желании можно добиться и `a.subscribe(fn)` без переписывания методов в цикле как в том же KnockoutJS. Тут нужно будет поисследовать насколько это быстрее/медленнее. Сейчас я просто давно уже перешёл на декораторы и `cellx.define`, так что уже не заморачиваюсь на эту тему)).

С тайпскриптом давно не работаю, раньше использовал эту типизацию: https://github.com/Riim/cellx/blob/master/src/cellx.d.ts . Стараюсь обновлять её стабильным функционалом, вроде должна быть рабочей.

**Comment by zerkalica** [comment]
по поводу #8, ну да, не берусь тут судить, производительность наверняка выше и памяти поменьше ест, если контекст не передавать ссылкой, а this использовать. 

Просто выглядит не очень очевидно с контекстом, но это из-за решения проблемы "как сделать код с атомами похожий на код без атомов с минимальным оверхедом".

Про интерфейс, формально он есть и рабочий, но на мой взгляд больше для галочки. Я про интерфейс именно фасада cellx, сам класс Cell то норм.

``` ts
interface Cell<T> {
        get(): T;
...
}

interface ICellx<T> {
        (value?: T): T;

        (
            method: string,
            arg1: any,
            arg2?: any,
            arg3?: any,
            arg4?: any,
            arg5?: any
        ): ICellx<T> | Error | Promise<any> | Cell<T>;
    }

var a: ICellx<number>
a('test', 'some').get() // Property get does not exists...
```

**Comment by Riim** [comment]
Поправил типизацию: https://github.com/Riim/cellx/blob/01457e694f436ca93d80e58f44a3deeff36da67e/src/cellx.d.ts#L231-L250 .

**Comment by zerkalica** [comment]
о, теперь понятно, спасибо.

Немного отвлеченный вопрос, а не мог бы ты описать трюки, которые позволяют увеличить производительность и снизить потребления памяти. Примерно как [Optimization-killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) у petkaantonov.

Есть общеизвестные - не использовать генерацию функций, миксины вместо new Class, но может в твоем опыте что-то еще есть?

**Comment by Riim** [comment]
Вряд ли мой опыт заметно отличается от того, что можно найти в Интернете, но я подумаю)).

**Comment by zerkalica** [comment]
Т.к. cellx.transact добавлен и моя хотелка выполнена, тикет закрою.
