### ISSUE TITLE
Функция в качестве значения атома, а не pull

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#16]
Нет ли способа использовать функцию без объектов-оберток в качестве значения атома cellx(fn)? Сейчас он пытается функцию вычислять.

Я хочу сделать hot-reloading, а в нем, когда мы меняем код, то меняется экспортируемый модулем класс, если бы класс был реактивным значением, то можно было заново его переинициализировать со старыми значениями.

```ts

import cellx from 'cellx'

interface IA {}

class A implements IA {}
class B implements IA {}

const classA = cellx(A)
const argsA = cellx([])

const a = cellx(() => new classA.get()(...argsA.get()))

a.get() instanceof A

classA.set(B)

a.get() instanceof B

```

**Comment by Riim** [comment]
Можно так:

``` js
let a = cellx(() => function() {});
```

**Comment by zerkalica** [comment]
Спасибо, работает
