### ISSUE TITLE
Возможность извлечь cell из метаданных объекта

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#17]
Есть ли способ извлечь ячейку из метаданных объекта, если таковой передается как значение?
Например,
```js
const o = cellx({a: 1})
const s = Symbol('cellx')

o[s].set({a: 2})
```

Просто делая atmover, я стремлюсь максимально тонкую прослойку делать с cellx, сейчас ко всем значениям-объектам добавляю свойство-символ с ссылкой на cellx, может оно уже где-то добавляется в cellx?

**Comment by Riim** [comment]
Не уверен, что правильно понял вопрос, но если нужно получать экземпляр `cellx.Cell` по обёртке `cellx`, то можно так:

``` js
let a = cellx(1);
let aCell = a('unwrap', 0);
console.log(aCell.get());
// => 1
```

А вообще, обёртка заточена больше для обычного использования, делать обёртку над обёрткой как-то, наверно, не очень хорошо, да и в таком случае от неё больше проблем, чем пользы. Я в таких случаях обычно перехожу на прямое использование `cellx.Cell`.

**Comment by zerkalica** [comment]
Да это все мои попытки сделать код с атомами, похожий на код без атомов, без использования get/set модификаторов, функций и т.д.

Пока сыро, но есть некий [opti-update](https://github.com/zerkalica/opti-update), который по задумке должен управлять очередями загрузки, обновлять/откатывать атомы при фейле, позволять делать retry/abort, некий low-cost optimistic updates, похожее есть в [relay](https://facebook.github.io/relay/docs/guides-mutations.html#optimistic-updates).

``` js
const Cell = cellx.Cell
const cid = Symbol('cellx:atom')

const getAtom: (v: V) => Atom<V> = (v: Object) => v[cid]
const createQueue = () => new Updater(getAtom, cellx.transact)

const a: A = {v: 1}
a[cid] = new Cell(a)

// ...
// Транзакция выглядит так примерно
syncedQueue1.transact()
    .set({...a, v: 2})
    .run()
```

Т.е. syncedQueue1 через абстракцию getAtom, получает из нового значение атом и дергает set.

**Comment by Riim** [comment]
Ага, дошло, в общем нет, ячейка никак не меняет данные, можно попробовать настроить такое поведение:

``` js
let s = Symbol('cellx');
let a = new cellx.Cell({}, { merge: function(value) {
    value[s] = this;
} });

let data = {};
a.set(data);

console.log(data[s] == a);
// => true
```

**Comment by zerkalica** [comment]
А что делает merge?

**Comment by Riim** [comment]
validate -- проверяет данные, в нём можно бросить ошибку если что не так  
merge -- обрабатывает данные, можно поменять объект, можно вообще вернуть новый:

``` js
merge(value) { return { ...value }; }
```

put -- записывает данные в ячейку, попутно можно записать их ещё куда-то, в тот же localStorage или отправить на сервер, по сути это обратная для pull функция и она тоже может быть асинхронной.

[Cell.js#L827-L834](https://github.com/Riim/cellx/blob/af96456ea1e3c2247f912923a36abb100f0886cb/src/Cell.js#L827-L834).

**Comment by zerkalica** [comment]
Ок. Думаю, стоит написать об этом прямо тут - https://github.com/Riim/cellx/blob/master/src/cellx.d.ts#L152

Я бы этот cellx.d.ts сделал основной документацией, остальное - вода.
