### ISSUE TITLE
Добавь пожалуйста нормальные интерфейсы на type в IEvent

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#18]
В IEvent сейчас type: string https://github.com/Riim/cellx/blob/master/src/cellx.d.ts#L23

Из документации не понятно, там только change или еще какие-нибудь могут быть?

**Comment by Riim** [comment]
Сейчас генерируются только `change` и `error`.

**Comment by Riim** [comment]
Поправил ICellEvent: https://github.com/Riim/cellx/commit/7efa03fe9a5a9d25b7b8a86d547f8ad92aaa0b30#diff-d95659a16eb27b8ba3bc90cb3cdb63f9R160 .

**Comment by zerkalica** [comment]
Разве структура event для разных type не отличается? Не лучше ли union-типы использовать для таких вещей?

``` js
// @flow

type IEvent = {
  type: 'error';
  error: Error;
} | {
  type: 'change';
  oldValue: mixed;
  value: mixed;
}
```

**Comment by zerkalica** [comment]
Не думал в subscribe заменить 2 аргумента одним? Там первый аргумент - error, напрашивается в event

**Comment by Riim** [comment]
Поправил, `v1.6.64`.

> Не думал в subscribe заменить 2 аргумента одним?

здесь политика как в ноде -- разработчик чтобы добраться до `evt` вынужден будет написать `err`, ну и написав он вспомнит, что неплохо бы ещё и обработать этот `err`.

**Comment by zerkalica** [comment]
Ну может и норм так, эти ужасные колбэки ноды напрямую сейчас не понятно зачем использовать, если есть всякие Promisify. Производительность разве.
