### ISSUE TITLE
Accessing any cell causes all change events to be fired?

### ISSUE THREAD

**Issue by dgreensp** [Riim/cellx#2]
```
a = cellx(1);
b = cellx(10);
c = cellx(() => a() + b());

c('subscribe', () => { console.log("C is", c()); })

a(2); a(3); // "C is 13"
a(4); b(); a(5); // "C is 14" "C is 15"
```

In this example, just getting `b()` apparently causes `c` to be recalculated and change events to fire.  That would mean you have to be very careful not to read any cells if you want multiple changes to result in one change event.

**Comment by Riim** [comment]
Hi. This behavior made for an another situation: when reading the calculated cell it can depend on changes made, to calculate this without applying changes can be quite difficult, faster immediately to apply changes. In the example above reads not calculated cell, it is guaranteed not to depend on any changes and here I fixed it, but when reading the calculated cell situation still remains and yet I don't see way to completely get rid of it without sacrificing performance.
