### ISSUE TITLE
Bug с  isPending

### ISSUE THREAD

**Issue by zerkalica** [Riim/cellx#20]
Тут никогда не сработает ресорв b:
```js
let a = new cellx.Cell((push, fail, oldValue) => {
  setTimeout(() => {
     push(1)
  }, 500)
  return oldValue || 0
});


let b = new cellx.Cell((push, fail, oldValue) => {
  setTimeout(() => {
     push(2)
  },700)
  return oldValue || 0
});

var c = new cellx.Cell(() => a.get() + b.get())
var d = new cellx.Cell(() => ({
  isPending: c.isPending(),
  c: c.get()
}))

d.subscribe((err, {value}) => {
  if (err) {
    console.error(err)
  }
  console.log('d.c = ' + value.c + ', d.isPending = ' + value.isPending)
})

const value = d.get()
console.log('start, d.c = ' + value.c + ', d.isPending = ' + value.isPending)


// "start, d.c = 0, d.isPending = false"
// "d.c = 1, d.isPending = true"
```

"d.c = 3, d.isPending = false" никогда не покажется.

http://jsbin.com/kuzuquzupe/edit?js,console

**Comment by Riim** [comment]
isPending ячейки не влияет на isPending зависимых ячеек. Нужно как-то так:

``` js
let a = new cellx.Cell((push, fail, oldValue) => {
  setTimeout(() => {
     push(1)
  }, 500)
  return oldValue || 0
});

let b = new cellx.Cell((push, fail, oldValue) => {
  setTimeout(() => {
     push(2)
  },700)
  return oldValue || 0
});

let c = new cellx.Cell(() => a.get() + b.get());
let cPending = new cellx.Cell(() => a.isPending() + b.isPending());
```

**Comment by zerkalica** [comment]
Я там в #7 спрашивал, тут еще раз спрошу, ты не считаешь нужным делать isPending наследуемым в computable-значениях? Это чем-то плохо или просто нет времени?

По сути пример с `let cPending = new cellx.Cell(() => a.isPending() + b.isPending());` нарушение инкапсуляции, т.к. рассказываем cPending о a и b, хотя теоретически информацию можно вытянуть из c.

**Comment by Riim** [comment]
> Это чем-то плохо или просто нет времени?

да вроде не плохо, сейчас быстро не получилось сделать, завтра попробую ещё раз.

**Comment by Riim** [comment]
Поправил в `1.6.68`. Определение `c` нужно поправить так, чтобы в нём был вызов `push`:

``` js
var c = new cellx.Cell(push => { push(a.get() + b.get()); });
```

**Comment by Riim** [comment]
С `1.6.70` `push` не обязателен.
