### ISSUE TITLE
Untranslated part of README

### ISSUE THREAD

**Issue by gamtiq** [Riim/cellx#30]
[Part of README.md about cellx.define](https://github.com/Riim/cellx#%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-cellxdefine) is not translated to English.

**Comment by Riim** [comment]
Done.
