### ISSUE TITLE
Одно вычисление а не два

### ISSUE THREAD

**Issue by DDD329** [Riim/cellx#32]
Привет! Ты не мог ли немного пояснить за счет чего достигается след. фича: есть три переменных a,b,c, где c = a() + b(); Если мы меняем a и b, то c вычисляется единожды.

**Comment by Riim** [comment]
Привет. При изменении `a` вычисления `c` не происходит, вместо этого `a` добавляется в [коллекцию изменённых ячеек](https://github.com/Riim/cellx/blob/a91e6159e38b7c6b082dfbb8d220090a3660e57a/src/Cell.js#L18) и ставиться nextTick (setTimeout 0) в котором произойдёт вычисление. Дальше меняется `b`, он тоже добавляется в ту же коллекцию, nextTick уже не ставится, тк один уже есть. Всё это происходит [здесь](https://github.com/Riim/cellx/blob/a91e6159e38b7c6b082dfbb8d220090a3660e57a/src/Cell.js#L637). Дальше срабатывает nextTick в котором всё считается один раз. Есть ситуации в которых сделанные изменения нужны немедленно, например:
```js
let a = cellx(1);
let b = cellx(2);
let c = cellx(() => a() + b());

a(5);
console.log(c()); // здесь расчёт изменений нужен ещё до срабатывания nextTick
b(10);
console.log(c()); // и здесь
```
поэтому методы создающие такие ситуации (get, on, off, disable) [запускают](https://github.com/Riim/cellx/blob/a91e6159e38b7c6b082dfbb8d220090a3660e57a/src/Cell.js#L694-L696) расчёт синхронно и в данном примере `c` посчитается два раза.

**Comment by DDD329** [comment]
Спасибо за ответ.
Действительно хорошая библиотека, мне она очень понравилась!
Мне понравился API с помощью которого создаются зависимые переменные.
