### ISSUE TITLE
Как сделать подписку с учётом будущих изменений?

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Riim/cellx#34]
Приветствую. Спасибо за интересный проект.

Сразу скажу: я — тупой. Реактивное программирование и в целом программирование для меня скорее вынужденное занятие, но тем не менее РП меня заинтересовало своей гибкостью.

Захотел сделать асинхронный конвейер событий где можно жить с коллбеками в коллбеках, но столкнулся с проблемой.
Вот упрощённый пример:
```javascript
var queueHack = function(level) {
	var count = 0;
	for (var key in level) {
		count++;
		if (level[key]() !== true && count !== 1) {
			return false;
		}
	}
	return true;
};
var test = cellx(function() {
	return queueHack(this);
});
test["a"] = cellx();
test["b"] = cellx(function() {
	return queueHack(test["b"]);
});
test["b"]["a"] = cellx();
test["b"]["b"] = cellx();
test["c"] = cellx();
test["a"](true);
test["b"]["a"](true);
test["b"]["b"](false);
test["c"](true);
test();
// false
```
Тут всё хорошо, но стоит написать так:
```javascript
var queueHack = function(level) {
	var count = 0;
	for (var key in level) {
		count++;
		if (level[key]() !== true && count !== 1) {
			return false;
		}
	}
	return true;
};
var test = cellx(function() {
	return queueHack(this);
});
test("subscribe", function(err, evt) {
	if (err) {
		console.log("error", err); return;
	}
	console.log("evt", evt);
})
test["a"] = cellx();
test["b"] = cellx(function() {
	return queueHack(test["b"]);
});
test["b"]["a"] = cellx();
test["b"]["b"] = cellx();
test["c"] = cellx();
test["a"](true);
test["b"]["a"](true);
test["b"]["b"](false);
test["c"](true);
test();
// true
```
Как видно после подписки последующие изменения уже не учитываются. 
Так и должно быть?

Проблема в том что в моей задаче сначала декларативно через функцию создаётся родительная ячейка и сразу же на неё делается подписка, а уже потом в неё могут дополниться дополнительные ячейки.
В общем я делаю очередь с иерархией подписок:
1.
1.1.
1.1.1
1.1.2
1.1.3
1.2.
1.2.1
1.2.2
1.2.3
Где каждый подуровень это каллбек (XHR внутри которого обращение к БД).
Точнее говоря тут в одном цикле вызывается каллбек, потом внутри этого каллбека ещё один цикл который вызывает ещё один каллбек и мне надо когда все они закончат работу вызвать событие.
Вот попытался клетки под это адаптировать, но не вышло.
Я скорее всего делаю что-то не так, но моих навыков не хватает понять как правильнее.
Поэтому сейчас пытаюсь сделать это более классической очередью событий, но подумал и посчитал нужным что стоит написать про проблему с подпиской.

**Comment by Riim** [comment]
При подписке `test("subscribe",` ячейка вычисляется и кеширует своё значение, дальше добавляются новые подячейки, но тк. ячейка сама не является наблюдаемой коллекцией, то она никак не реагирует на это и при чтении `test();` выдаётся значение, которое было вычислено в момент подписки. Тут либо насильно заставлять её перевычисляться после добавления подъячеек:
```js
// ...
test('pull', 0);
test();
```
либо, что намного лучше, строить дерево ячеек на основе наблюдаемой коллекции, здесь подойдёт [ObservableMap](https://github.com/Riim/cellx#cellxobservablemap):
```js
class Node {
	constructor() {
		this.children = new cellx.ObservableMap(null, { adoptsValueChanges: true });
		this.childrenCell = new cellx.Cell(this.children);

		this.ok = new cellx.Cell(function() {
			let children = this.childrenCell.get();

			if (children.size) {
				for (let [key, value] of children) {
					// Не очень понял суть оригинального условия, поэтому упростил и учёл в нём,
					// что значением может быть подузел: если значение не узел, то просто смотрим значение,
					// если узел, то смотрим его 'ok', который будет вычислен из значений и подузлов этого узла.
					if ((value instanceof Node ? value.ok.get() : value) !== true) {
						return false;
					}
				}
			}

			return true;
		}, { owner: this });
	}

	setChild(key, value) {
		this.children.set(key, value);
		return value;
	}
}

let test = new Node();

test.childrenCell.on('change', evt => {
	// console.log(1, evt.value);
});

test.setChild('a', undefined); // test["a"] = cellx();
let b = test.setChild('b', new Node()); // test["b"] = cellx(function() { return queueHack(test["b"]); });
b.setChild('a', undefined); // test["b"]["a"] = cellx();
b.setChild('b', undefined); // test["b"]["b"] = cellx();
test.setChild('c', undefined); // test["c"] = cellx();

test.children.set('a', true); // test["a"](true);
b.children.set('a', true); // test["b"]["a"](true);
b.children.set('b', false); // test["b"]["b"](false);
test.children.set('c', true); // test["c"](true);

console.log(test.ok.get()); // false

b.children.set('b', true);

console.log(test.ok.get()); // true
```

**Comment by 0x4E69676874466F78** [comment]
Благодарю за ответ.
> либо насильно заставлять её перевычисляться после добавления подъячеек

Да что-то вроде такое подумал, только в сторону отписки и подписки заново, а вот о pull не в курсе, оно не документировано и видимо для внутренних нужд? 

С ObservableMap попробую разобраться, спасибо за отправную точку.

> Не очень понял суть оригинального условия

Речь про     
```javascript
	for (var key in level) {
		count++;
		if (level[key]() !== true && count !== 1) {
			return false;
		}
	}
```
?
Там просто первым узлом идёт сырая функция i(t)
Увидеть её можно если добавить ```console.log(level[key]())``` внутри for (var key in level)
Я просто так скостылял её пропуск.

**Comment by Riim** [comment]
> о pull не в курсе, оно не документировано и видимо для внутренних нужд?

не документирован, но он никуда не денется в следующих версиях, и будет хорошо описан при переписывании доки. В общем, можно пользоваться.

**Comment by 0x4E69676874466F78** [comment]
С новым синтаксисом JS я пока ещё толком не знакомился, так что туплю ещё сильнее тут.
Из выше примера не понятно как повторить вариант с моим примером, который выглядит так:
```javascript
var queueHack = function(level) {
	var count = 0;
	for (var key in level) {
		count++;
		if (level[key]() !== true && count !== 1) {
			return false;
		}
	}
	return true;
};
var test = cellx(function() {
	return queueHack(this);
});
test["a"] = cellx();
test["b"] = cellx(function() {
	return queueHack(test["b"]);
});
test["b"]["a"] = cellx();
test["b"]["b"] = cellx();
test["c"] = cellx();
test("subscribe", function(err, evt) {
	if (err) {
		console.log("error", err); return;
	}
	console.log("evt", evt);
})
test["a"](true);
test["b"]["a"](true);
test["b"]["b"](false);
test["c"](true);
test(); 
// false
test["b"]["b"](true); 
// evt Object {target: u, type: "change", oldValue: false, value: true, prev: null}
// true
test["b"]["b"](false); 
// evt Object {target: u, type: "change", oldValue: true, value: false, prev: null}
// false
test["b"]["a"](false);
// false
test["b"]["b"](true);
// true
test["b"]["a"](true);
// evt Object {target: u, type: "change", oldValue: false, value: true, prev: null}
// true
```
В примере ObservableMap когда делается подписка на children или childrenCell поведение совсем другое.
Как сделать чтоб событие сработало только когда все подъячейки отдадут true?
То есть тут грубо говоря дерево уровней, на корневой узел каждого подписка которая сработает когда все его дочерние ячейки отдадут true. Выше для упрощения подписка только на самый корень.

А для грязного трюка с test('pull', 0); придётся скостылять, ибо при его вызове вызывается обработчик:
```javascript
evt Object {target: u, type: "change", oldValue: true, value: false, prev: null}
true
```
хотя я ячейкам ещё не задавал состояния, только инициализировал.

**Comment by Riim** [comment]
Подписываться нужно на `ok`, концовка получается такая:
```js
// Заполняем
test.setChild('a', undefined); // test["a"] = cellx();
let b = test.setChild('b', new Node()); // test["b"] = cellx(function() { return queueHack(test["b"]); });
b.setChild('a', undefined); // test["b"]["a"] = cellx();
b.setChild('b', undefined); // test["b"]["b"] = cellx();
test.setChild('c', undefined); // test["c"] = cellx();

// Подписываемся
test.ok.on('change', function(err) {
	if (err.value) {
		console.log('Выполнено');
	}
});

// Меняем значения пока `ok` не станет true
test.children.set('a', true); // test["a"](true);
b.children.set('a', true); // test["b"]["a"](true);
b.children.set('b', false); // test["b"]["b"](false);
test.children.set('c', true); // test["c"](true);

console.log(test.ok.get()); // false

b.children.set('b', true);
// 'Выполнено'

console.log(test.ok.get()); // true
```

`childrenCell` принимает в качестве значения `ObservableMap`, когда в ячейке оказывается значение наследующее от `cellx.EventEmitter`, она подписывается на его событие `change` и начинает сама изменяться при этом событии, даже если значение в ячейке не заменялось на другое. С `childrenCell` как раз так и происходит, это промежуточная ячейка создана для того, чтобы ячейка `ok` могла реагировать на изменения в `children`, если просто заиспользовать `children` в формуле ячейки `ok`, то она не подпишется на его `change`. Это так, для общего понимания происходящего)).

`adoptsValueChanges: true` кстати можно убрать, я сначала по-другому хотел сделать, но в получившемся варианте он не нужен.

**Comment by 0x4E69676874466F78** [comment]
> Подписываться нужно на ok

Что-то я протупил сильнее обычного, хотя смотрел в код и обращал внимание на это ok. 
Большое спасибо!
