### ISSUE TITLE
Сломаны removeChangeListener и unsubscribe

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Riim/cellx#35]
Для примера
```javascript
test = cellx();
test("subscribe", function(err, evt) {
	console.log("evt", evt);
})
test("unsubscribe", 0)
test("unsubscribe", undefined) // Uncaught TypeError: Cannot read property 'Symbol(wrappers)' of undefined
test("unsubscribe", function(){})
```
Всё варианты не работают.
Аналогично с removeChangeListener.
Что удивительно 
```javascript
test("dispose", 0)
```
удалило подписку, а сама ячейка осталась жива и работоспособна.

**Comment by Riim** [comment]
`unsubscribe` вторым параметром должен принимать обработчик, который ранее был использован в `subscribe`:
```js
test = cellx();
let listener = function(err, evt) {
	console.log("evt", evt);
};
test("subscribe", listener)
test("unsubscribe", listener)
```

**Comment by 0x4E69676874466F78** [comment]
Ага, понял. Так работает.
Но из справки это не очевидно ибо:
```javascript
user.fullName('subscribe', function(err, evt) {
    if (err) {
        //
    } else {
        //
    }
});
```
тут нет обработчика и сразу передаётся функция. Стоит её тогда подправить.
Если попробовать передать как есть
```javascript
test = cellx();
test("subscribe", function(err, evt) {
	console.log("evt", evt);
})
test("unsubscribe", function(err, evt) {
	console.log("evt", evt);
})
```
то отписка не произойдёт, то есть получается от такой подписки уже нормальным способом не отписаться, об этом тоже стоит написать в справке.
Зачем нужно именно обработчик передавать? Это сделано в случае когда их несколько подписано разных? Но почему тогда если там указывается 0 не отписать сразу все обработчики?

**Comment by Riim** [comment]
> то есть получается от такой подписки уже нормальным способом не отписаться

ну да, только через `dispose`, тут сделано однотипно с нативными `addEventListener` и `removeEventListener`, так вполне привычно для тех кто постоянно на js пишет. Доку я скорей всего буду полностью переписывать, сейчас в ней в основном описана функция `cellx`, которая является обёрткой над классом `cellx.Cell`. Такая обёртка имела смысл когда в языке не было ни аксессоров, ни декораторов, сейчас она больше вопросов создаёт, тот же `0` в `dispose` -- вообще костыль, он передаётся чтобы получалось два параметра, один параметр расценивается как запись в ячейку.

В общем, сейчас лучше вместо:
```js
let valueCell = cellx(1);
valueCell('subscribe', listener);
valueCell('addChangeListener', listener);
valueCell(5);
valueCell('dispose', 0);
```
работать напрямую с `cellx.Cell`:
```js
let valueCell = new cellx.Cell(1);
valueCell.subscribe(listener);
valueCell.on('change', listener);
valueCell.set(5);
valueCell.dispose();
```
или через `cellx.define` создавать наблюдаемые поля в классах:
```js
class Test extends cellx.EventEmitter {
    constructor() {
        cellx.define(this, {
            value: 1
        });

        this.on('change:value', this._onValueChange, this);
        this.value = 5;
    }
}
```
или если доступны декораторы (typescript, babel):
```js
import { observable, computed } from 'cellx-decorators'; // https://www.npmjs.com/package/cellx-decorators
class Test extends cellx.EventEmitter {
    @observable value = 1;

    constructor() {
        this.on('change:value', this._onValueChange, this);
        this.value = 5;
    }
}
```

**Comment by 0x4E69676874466F78** [comment]
Понял, спасибо.
