### ISSUE TITLE
consider switching to Rollup

### ISSUE THREAD

**Issue by leeoniya** [Riim/cellx#38]
hey @Riim

Rollup produces better/smaller bundles than Webpack; there is less internal boilerplate.

you'll probably want to use something like rollup-plugin-typescript with it.

https://github.com/rollup/rollup-plugin-typescript

**Comment by leeoniya** [comment]
actually, you'll need rollup-plugin-typescript2, which supports exporting interfaces. this worked for me:

rollup.config.js:

```js
import typescript from 'rollup-plugin-typescript2';

export default {
  input: './src/cellx.ts',
  output: {
    file: './dist/cellx.umd.js',
    format: 'umd',
    name: 'cellx',
  },
  plugins: [
    typescript()
  ]
}
```


tsconfig:

```
"module": "ES2015",
```

size reduction of cellx.umd.js:

45.0KB -> 39.8KB

**Comment by Riim** [comment]
Hi, done in `v1.9.1`

**Comment by leeoniya** [comment]
nice.

node_modules is still huge :(

https://packagephobia.now.sh/result?p=jest
38.6MB

there are much smaller testing frameworks than jest. for example, mocha + nyc (for coverage) is smaller.

https://packagephobia.now.sh/result?p=awesome-typescript-loader
6.48MB

probably no longer needed since dropping webpack?

i've opened an issue for rollup-pluginutils to update to latest micromatch, too. (this should save 2MB).

https://github.com/rollup/rollup-pluginutils/issues/65

also https://github.com/ezolenko/rollup-plugin-typescript2/issues/161

you can drop `package.json` into here and see what sticks out:  http://npm.broofa.com/. it only analyzes `dependencies`, so just copy over `devDependencies` into `dependencies`.

**Comment by Riim** [comment]
@leeoniya ok, thanks.

**Comment by leeoniya** [comment]
@Riim new rollup-plugin-typescript2 is out with 2MB smaller `node_modules`.
