### ISSUE TITLE
@observer decorator for React

### ISSUE THREAD

**Issue by imran-kaif** [Riim/cellx#4]
@observer decorator for React like in [mobx](https://mobxjs.github.io/mobx/refguide/observer-component.html)?

**Comment by Riim** [comment]
Привет. Воскресил старые наработки: [cellx-react](https://github.com/Riim/cellx-react), вроде даже всё хорошо работает, но сам уже давно не пользовался. Если что, пиши здесь или лучше [здесь](https://github.com/Riim/cellx-react/issues/new).

**Comment by imran-kaif** [comment]
Thanks!
