### ISSUE TITLE
create-react-app TypeError: undefined has no properties _on EventEmitter.js:102

### ISSUE THREAD

**Issue by demon24ru** [Riim/cellx#40]
В последнем релизе при подписи на события изменения:
````
class Sstore extends EventEmitter {
    constructor(s) {
        super();
        this.store = cellx(s);
    }
}

const test = new Sstore(55);
test.on('change:store', ()=>{\*   *\});
````

Ошибка: _on: EventEmitter.js:102

**Comment by Riim** [comment]
```js
// Вариант первый, самый старый, появился когда в javascript ещё не было аксессоров.
// Наследоваться от EventEmitter в первом варианте не обязательно.

class Sstore extends EventEmitter {
    constructor(s) {
        super();
        this.store = cellx(s);
    }
}

const test = new Sstore(55);

// Подписка:
test.store.on('change', ()=>{\*   *\});
// или
test.store.onChange(()=>{\*   *\});

// Чтение:
test.store(); // 55
// Запись:
test.store(5);

// Вариант второй.
// В javascript появились аксессоры.

import { define } from 'cellx';

class Sstore2 extends EventEmitter {
    constructor(s) {
        super();
        define(this, {
            store: s
        });
    }
}

const test2 = new Sstore2(55);

// Подписка:
test2.on('change:store', ()=>{\*   *\});

// Чтение:
test.store; // 55
// Запись:
test.store = 5;

// Вариант третий.
// В javascript появились декораторы через транспайлеры (babel, typescript).

import { Observable } from 'cellx-decorators';

class Sstore2 extends EventEmitter {
    @Observable
    store = null;

    constructor(s) {
        super();
        this.store = s;
    }
}

const test2 = new Sstore2(55);

// Подписка:
test2.on('change:store', ()=>{\*   *\});

// Чтение:
test.store; // 55
// Запись:
test.store = 5;

```

**Comment by Riim** [comment]
Расскажу как это внутри устроено, может пригодится.
В основе лежит класс [Cell](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/Cell.ts#L62). Всё остальное -- обёртки над ним. Первая обёртка -- функция [cellx](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L123), возвращает [рабочую функцию](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L127-L134) которой на свойство [cell](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L137) добавляется экземпляр класса Cell. Рабочая функция при вызове без аргументов [прочитает значение](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L133) из экземпляра Cell, а при вызове с аргументом [запишет его](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L129) в Cell. Так же у рабочей функции [подменяется прототип](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L135) в котором теперь добавлены [некоторые методы](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L66-L121). Все они просто проксируют вызовы на экземпляр Cell.

Вторая обёртка [defineObservableProperty](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L142) [прячет экземпляр Cell](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L147-L149) в Map-e хранимом на объекте (на котором определяется реактивное свойство) по символу [KEY_VALUE_CELLS](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L64). И создаёт на объекте [getter и setter](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/cellx.ts#L151-L162) проксирующие чтение/запись на спрятанный Cell. В спрятанном Map-е в качестве ключа -- имя свойства, значение -- соответствующий свойству экземпляр Cell. В классе [EventEmitter](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/EventEmitter.ts#L30) сделан костыль, который, [видя в типе события двоеточие](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/EventEmitter.ts#L160), тоже [лезет в спрятанный Map](https://github.com/Riim/cellx/blob/39a487ed0b0142ff20adbdecdabf817095536733/src/EventEmitter.ts#L164-L168) для добавления обработчика к экземпляру Cell.

Третья обёртка в виде декораторов Observable и Computed так же как и вторая работает с тем же Map-ом, но getter и setter создаются теперь через декораторы сразу на прототипе класса, а не через вызов метода defineObservableProperty в конструкторе. Это немного выгоднее по памяти, тк. getter и setter теперь определены в прототипе для всех экземпляров, а не создаются новые для каждого.

**Comment by demon24ru** [comment]
Вариант с define согласен, работает.
Первый вариант конечно, в таком виде, сработает потому что мы обращаемся непосредственно к атрибуту класса обернутого в Cell который имеет возможность непосредственно подписаться на данную ячейку.
А вот последний вариант не сработает в таком виде, выдает ошибку указанную выше.

**Comment by Riim** [comment]
Поправьте в третьем варианте `test` на `test2` в последних двух строчках и всё заработает.

**Comment by demon24ru** [comment]
На ошибки в примере, приведенном Вами выше, там все понятно с названиями переменных. Конкретно данный пример выдает ошибку попробуйте у себя.
````
import {Observable} from 'cellx-decorators';

class Sstore extends EventEmitter {

    @Observable store = null;

    constructor(s) {
        super();
        this.store = s;
    }
}

const ss = new Sstore(55);

ss.on('change:store', (evt) => {
     console.log('ss', evt);
 });
````

"cellx": "1.10.8",
"cellx-decorators": "1.6.2"

**Comment by Riim** [comment]
В typescript без проблем заработало. У вас babel?

**Comment by demon24ru** [comment]
да babel плюс зависимости:
````
// config-overrides.js

const {
    addDecoratorsLegacy,
    override,
    disableEsLint,
    addBabelPlugins
} = require("customize-cra");

module.exports = override(
    disableEsLint(),
    addDecoratorsLegacy(),
    addBabelPlugins(
        "@babel/plugin-proposal-export-default-from"
    )
);
````
````
// package.json

"devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.10.1",
    "@babel/plugin-proposal-export-default-from": "^7.10.1",
    "customize-cra": "^1.0.0",
    "react-app-rewired": "^2.1.6"
  }
````

**Comment by demon24ru** [comment]
Ошибка в этой функции из node_modules/cellx/dist/EventEmitter.js
````
_on(type, listener, context) {
        let index;
        if (typeof type == 'string' && (index = type.indexOf(':')) != -1) {
            let propName = type.slice(index + 1);
            currentlySubscribing = true;
>>Здесь>>   ((this[KEY_VALUE_CELLS] || (this[KEY_VALUE_CELLS] = new Map())).get(propName) || (this[propName], this[KEY_VALUE_CELLS]).get(propName)).on(type.slice(0, index), listener, context);
            currentlySubscribing = false;
        }
        else {
            let events = this._events.get(type);
            let evt = { listener, context };
            if (!events) {
                this._events.set(type, evt);
            }
            else if (Array.isArray(events)) {
                events.push(evt);
            }
            else {
                this._events.set(type, [events, evt]);
            }
        }
    }
````

**Comment by demon24ru** [comment]
При той же конфигурации babel на версии cellx 1.10.5 все работает.

**Comment by Riim** [comment]
Попробуйте обновить cellx-react до последней версии. Должно заработать. Если не заработает, то посмотрите настройки babel-я вот в этом проекте [react-cellx-todo-app](https://github.com/Riim/react-cellx-todo-app). Я обновил там всё до последних версий.

**Comment by demon24ru** [comment]
Выяснил в чем проблема была и есть:
После смены версии компилятора typescript с версии 3.8.* на 3.9*, он неправильно компилит работу с контекстом.
После того как перекомпилил исходник cellx на версии 3.8 все стало работать правильно с теми зависимостями babel что указывал выше.

С react-cellx-todo-app все работает и так, надо разбираться дальше какие плагины бабеля неправильно понимают скомпилированое typescript 3.9* версии.

**Comment by Riim** [comment]
Могу просто перекомпилить версией 3.8.*. Нужно?

А почему неправильно?
```js
export class Cell extends EventEmitter {
}
```
Заменяет на:
```js
let Cell = /** @class */ (() => {
    class Cell extends EventEmitter {
    }
    return Cell;
})();
export { Cell };
```
Вроде всё корректно, хоть и непонятно зачем.

**Comment by demon24ru** [comment]
Извиняюсь, неправильно выразился.

В зависимости нужно добавить плагин: 
@babel/helper-call-delegate 
и все заработает.
Проблема решена.

**Comment by demon24ru** [comment]
За поправку cellx-react отдельное спасибо.
