### ISSUE TITLE
Error rethrowed only once

### ISSUE THREAD

**Issue by nin-jin** [Riim/cellx#41]
```js
a = cellx(0)
b = cellx(()=>{ console.xxx() })
b() // cellx.umd.js:45 TypeError: console.xxx is not a function
b() // undefined
```

Второй обратившийся к ячейке вместо актуального значения или исключения получает undefined и скорее всего его логика тоже сломается и бросит уже другое исключение. И так каскадом.

**Comment by Riim** [comment]
При первом вызове `b` тоже будет undefined. Актуальным значением считаю последнее какое удалось вычислить, в данном случае успешного вычисления не было совсем, т.е. актуальное значение -- undefined. Что касается ошибки -- это не значение, а состояние, лежит в свойстве _error (надо бы геттер к нему сделать), распространяется на все реакции (зависимые ячейки) и на него можно подписаться (в т.ч. в реакциях).
Вызывающий код не подает с ошибкой даже если вызов происходит в пассивной ячейке:
```js
let a = cellx(() => {
	console.log(3);
	console.xxx();
});
let b = cellx(() => {
	console.log(2);
	let b_ = a();
	console.log(4);
	return b_;
});
console.log(1);
console.log('b:', b());
console.log(5);
console.log('b:', b());
```
Выводит:
```
1
2
3
TypeError: console.xxx is not a function
4
b: undefined
5
b: undefined
```
В пассивном режиме ячейка работает как функция с мемоизацией. Сброс запомненного значения происходит при записи в любую ячейку, но только если есть зависимости. Здесь у `a` нет зависимостей и не было записи, значит вычислять `a` нет никакого смысла. А вот `b` имея зависимости после записи уже перевычислится:
```js
let a = cellx(() => {
	console.log(3);
	console.xxx();
});
let b = cellx(() => {
	console.log(2);
	let a_ = a();
	console.log(4);
	return a_;
});
console.log(1);
console.log('b:', b());
console.log('Write to a');
a(1);
console.log(5);
console.log('b:', b());
```
Выводит:
```
1
2
3
TypeError: console.xxx is not a function
4
b: undefined
Write to a
5
2
4
b: 1
```
Обрати внимание, после `Write to a` при чтении `b` он перевычисляется, но вычисления `a` не происходит. Здесь `a` не вычисляется ещё и потому, что запись шла именно в него и после этого не было других записей, но с тем же успехом можно было записать в случайный `x` (пассивные ячейки не знают свои реакции, а значит сбрасывать запомненные значения нужно у всех других пассивных ячеек, кроме той в которую идёт запись).

А вот активная ячейка уже и  сама падает:
```js
let first = false;
let c = cellx(0);
let d = cellx(() => {
	c();

	console.log(3);

	if (!first) {
		first = true;
		return 1;
	}

	console.xxx();
});
let e = cellx(() => {
	console.log(2);
	let d_ = d();
	console.log(4);
	return d_;
});

e.onChange(() => {
	console.log('e onChange');
});

setTimeout(() => {
	console.log('Write to c');
	c(5);
}, 1);
```
Выводит:
```
2
3
4
Write to c
3
TypeError: console.xxx is not a function
```

**Comment by nin-jin** [comment]
В консоли проверял, не обратил внимание, что исключение логируется, но не кидается. Тем не менее описанная проблема наблюдается уже сразу:

```
let a = cellx.cellx(() => {
	console.log(3);
	getCount();
});
let b = cellx.cellx(() => {
	console.log(2);
	let b_ = a();
	console.log(4);
	return b_.toString();
});
console.log(1);
console.log('b:', b());
console.log(5);
console.log('b:', b());
```

```
1
2
3
ReferenceError: getCount is not defined
4
TypeError: Cannot read properties of undefined (reading 'toString')
b: undefined
5
```

Получается в логике нужно каждый раз проверять, а не пришёл ли undefined.

**Comment by Riim** [comment]
> Получается в логике нужно каждый раз проверять, а не пришёл ли undefined

Для активных ячеек нет, для пассивных да. Именно такого поведения я и добивался. Почти всегда всё находится и работает в активном состоянии и проблемы нет, а в пассивном варианте я хотел чтобы поведение ячейки минимально отличалось от поведения обычной функции (только мемоизацией).

**Comment by nin-jin** [comment]
Так обычная функция в случае ошибки кидает исключение, а не возвращает undefined.

**Comment by Riim** [comment]
Тут я имею ввиду не ячейку в которой случилось исключение (в первом моём примере это `a`), а читающую её ячейку (`b`). Вот её поведение в пассивном режиме не должно отличаться от поведения обычной функции, т.е. в читающей ячейке (`b`) не должно быть какой то реакции на исключение в читаемой ячейке (`a`) как это происходит в активном режиме. Что касается поведения ячейки с исключением (`a`), то тут я исключение воспринимаю как переход в состояние ошибки с сохранением ранее вычисленного значения, которое и возвращается (но только в пассивном режиме, в активном исключение пойдёт по реакциям).

**Comment by Riim** [comment]
Тебя наверно путает пассивный режим, если добавишь обработчик к `b`, то всё заработает как ты ожидаешь.

**Comment by nin-jin** [comment]
Меня пугает разное поведение в зависимости от наличия подписчиков и возникновение наведённых исключений тут и там.
Зачем вообще такой пассивный режим нужен?

**Comment by Riim** [comment]
> Зачем вообще такой пассивный режим нужен?

Зависимости не запоминают свои реакции, что позволяет сборщику мусора подбирать такие ячейки при необходимости. Это позволяет воспринимать ячейку как объект от которого нужно просто отписаться, иначе же его нужно воспринимать ещё и как обработчик, который сам нужно не забыть отписать от зависимостей. Я в чате видел ваше обсуждение про холодные/тёплые/горячие обсерваблы. Кажется такой пассивный режим соответствует тёплым обсерваблам. Не знаешь как такие варианты обсерваблов объясняют? Там тоже как-то со сборкой мусора связано или какая-то другая идея?

**Comment by nin-jin** [comment]
Когда `b` обращается к `a` зачем может потребоваться возвращать `undefined` вместо бросания исключения, которое, как я вижу, запоминается в `a`?
Эти термины сильно зависят от специфики библиотеки, так что 1-к-1 плохо мапятся.

**Comment by Riim** [comment]
Потому что чтение ячейки это чтение значения ячейки, а оно undefined. Случившаяся ошибка это вторая часть состояния ячейки, оно должно повлиять на активную цепочку, но не должно ложить другой код не относящийся к реактивности. Да, вот такая вот логика))

**Comment by nin-jin** [comment]
В результате экшены начинают сыпать случайными эксепшенами. Зачем так делать-то?

**Comment by Riim** [comment]
Ладно, убедил. Поправил как ты предлагаешь, посмотрим как оно будет себя вести.
