### ISSUE TITLE
Зачем `let reactions = this._reactions;`

### ISSUE THREAD

**Issue by gonzobard777** [Riim/cellx#42]
Привет.
А зачем перед какой-либо операцией над `this._reactions` ссылка на массив сначала копируется в отдельную переменную и уже над ней производится операция, например:
https://github.com/Riim/cellx/blob/11ba12c4317534fce1c797dbad17006d7a72d82d/src/Cell.ts#L702
?

**Comment by Riim** [comment]
Привет!

1. Иногда читабельней,
2. Быстрей. Я давно не тестировал этот момент, но раньше запись в переменную по скорости примерно равнялась чтению обычного свойства (не аксессора), то есть если свойство в среднем читается 3+ раз, то есть смысл прочитать его один раз записав в переменную.
