### ISSUE TITLE
Ожидание корректного значения

### ISSUE THREAD

**Issue by gonzobard777** [Riim/cellx#43]
Привет.

В случае rxjs значение из Observable может не выйти до тех пор, пока не сработает условие, например:
```js
ob$.pipe(
  ...
  filter(x => !!x),
)
```
Весь код, использующий `ob$`,  просто ждет значения.
Как сделать тоже самое на cellx?

**Comment by Riim** [comment]
RxJS содержит множество функциональных утилит, это довольно мощная и сложная библиотека. Cellx же - просто минималистичный движок. Можно записать в императивном стиле:
```js
const ob$ = cellx(false);
const ob2$ = cellx(() => {
    if (ob$()) {
        // ...
    }
});
```
Если хочется больше функциональщины, то pipe и filter прийдется написать самому. Думаю реально добиться чего-то вроде такого:
```js
const ob$ = cellx(false);
const ob2$ = cellx(pipe(ob$, [
    filter(x => !!x),
    // ...
]));
```
