### ISSUE TITLE
Почему dep._addReaction после pull делает ячейку DIRTY?

### ISSUE THREAD

**Issue by gonzobard777** [Riim/cellx#44]
Привет.

Вопрос конкретно по этой строчке:
https://github.com/Riim/cellx/blob/master/src/Cell.ts#L615

Почему передается actual false?

Например:
```typescript
const direct = new Cell(true);
const a = new Cell(() => direct.get() ? 3 : b.get());
const b = new Cell(() => c.get());
const c = new Cell(() => 9);

a.onChange(()=>{});
direct.set(false);
Cell.release();
expect(b._state).eq(CellState.DIRTY);
```

После `direct.set(false)`:

`a._pull()` -> `b._pull()` -> `c._pull()`

Вроде бы по логике состояние  b должно быть гарантированно ACTUAL.
Можешь объяснить как так?

**Comment by Riim** [comment]
Привет! Потому что продолбал этот момент. Поправил в `v1.10.27`. Спасибо, что заметил.
