### ISSUE TITLE
_deactivate() не чистит this._dependencies

### ISSUE THREAD

**Issue by gonzobard777** [Riim/cellx#45]
Привет.

после очистки всех зависимостей от реакции:
https://github.com/Riim/cellx/blob/master/src/Cell.ts#L482

`this._dependencies` же не чистится, соответственно, держит ссылки на зависимости, которые уже ничего не знают об этой реакции.

Если это норм, скажи зачем их хранить, ведь даже state стал DIRTY?

**Comment by Riim** [comment]
Привет!

Ссылки на реакции вычищаются для того чтобы сборщик мусора мог находить неиспользуемые ячейки и они не зависали в памяти. Обратные ссылки на зависимости этому никак не мешают, скорей всего можно и их чистить, но смысла усложнять здесь скорей всего нет.

**Comment by gonzobard777** [comment]
Пример:
```typescript
const a = new Cell(()=>b.get());
const b = new Cell(7);

const noop = ()=>{};
a.onChange(noop);
a.offChange(noop);
```
1. `b` не ссылается на `a`
2. но `a` так и ссылается на `b`

какую из ячеек gc посчитает неиспользуемой и удалить из памяти?

**Comment by gonzobard777** [comment]
походу понял, надо просто разомкнуть ссылку друг на друга, и тут по-идее не важно что чистим, могли почистить зависимости вместо реакций

**Comment by Riim** [comment]
> тут по-идее не важно что чистим

Всё же это важно)) В примере выше на `a` никто не ссылается, это и даёт GC возможность удалить его. То что сам `a` при это на кого-то ссылается ему (GC) пофик. Другими словами удаляется то, что не используется, если после удаления `a` GC увидит, что `b` тоже никому уже не нужен, то и его почистит.

**Comment by dwfe** [comment]
ага, понял, благодарю
