### ISSUE TITLE
Async cell

### ISSUE THREAD

**Issue by dwfe** [Riim/cellx#47]
Привет.

Почитал в редми и не смог понять как сделать асинхронную ячейку( Подскажи пожалуйста.
У меня есть такой Api:

```typescript
class Api {
  w = new Cell(() => this.triggerW.get());
  triggerW = new Cell(7);

  p = new Cell(() => this.triggerP.get());
  triggerP = new Cell(5);

  z = new Cell(() => this.triggerZ.get());
  triggerZ = new Cell(3);

  async request(): Promise<string> {
    const wResult = `w[${this.w.get()}]`;
    const pResult = await new Promise(resolve => {
      const pValue = this.p.get();
      setTimeout(() => resolve(`p[${pValue}]`), 50); // e.g. request to the server
    });
    return `${wResult} ${pResult} z[${this.z.get()}]`;
  }
}
```

Надо сделать что-то вроде такого:
```typescript
const api = new Api();
const rootCell = new Cell(() => asyncCell.get());
const asyncCell = new AsyncCell(() => api.request());
rootCell.onChange(event => {
  console.log('пришло из асинхронной ячейки:', event.data);
});
api.triggerW.set('hello world');
```

**Comment by Riim** [comment]
Не уверен, что понял пример. Вот простой пример АПИ на cellx:
```js
class BinanceAPI {
	serverTime = cellx(({ push, fail, wait }) => {
		fetch('https://api.binance.com/api/v1/time')
			.then((res) => res.json())
			.then(push, fail);

		wait();
	});
}

const binance = new BinanceAPI();

autorun(() => {
	console.log('autorun');
	console.log(binance.serverTime());

	setTimeout(() => {
		binance.serverTime.pull();
	}, 3000);
});
```
Выводит:
```
test.html:25 autorun
test.html:25 autorun
test.html:26 {serverTime: 1658241693094}
test.html:25 autorun
test.html:26 {serverTime: 1658241696386}
...
```
autorun -- это по сути вычисляемая ячейка с добавленным ей пустым обработчикам onChange, то есть она сразу в активном состоянии. Для уничтожения нужно вызвать возвращаемую ей функцию (внутри просто снимается пустой обработчик onChange).
При первом вызове autorun второй console.log не срабатывает, это из-за `wait()` (внутри serverTime) который просто бросает спец.ошибку которая останавливает всё вычисление, но не попадает в консоль. Система как бы переходит в режим ожидания из которого можно вывести вызовом `push(data)` или `fail(err)`. При вызове push ячейка serverTime запоминает переданное ей значение, а вычисляемая autorun-ячейка реагирует на это. Только на этот раз при чтении serverTime до wait уже не доходит, тк. ячейка не запускает своё вычисление, а просто возвращает запомненное значение, в результате, на этот раз, срабатывает второй console.log выводящий результат запроса.
Если теперь читать serverTime, то он всегда будет возвращать запомненный результат, что бы заставить его опять сходить на сервер нужно вызвать pull. Во время повторного запроса ячейка по прежнему будет иметь запомненное значение.  

Пример с цепочкой запросов:
```js
class BinanceAPI {
	exchangeInfo = cellx(({ push, wait }) => {
		fetch('https://api.binance.com/api/v1/exchangeInfo')
			.then((res) => res.json())
			.then(push);

		wait();
	});

	firstSymbolTicker = cellx(({ push, wait }) => {
		fetch(`https://api.binance.com/api/v1/ticker/bookTicker?symbol=${this.exchangeInfo().symbols[0].symbol}`)
			.then((res) => res.json())
			.then(push);

		wait();
	});
}

const binance = new BinanceAPI();

autorun(() => {
	console.log(binance.firstSymbolTicker());
});
```
Выводит:
```js
{
  symbol: 'ETHBTC',
  bidPrice: '0.06769500',
  bidQty: '6.40620000',
  askPrice: '0.06769600',
  askQty: '3.68580000'
}
```

**Comment by dwfe** [comment]
супер, то что надо, благодарю

**Comment by Riim** [comment]
Ещё немного добавлю. Вместо `wait()` можно возвращать какое-то значение, тогда ячейка на время запроса примет это значение. Ну и при первом вызове autorun второй console.log уже конечно сработает:
```js
class BinanceAPI {
	serverTime = cellx(({ push }, prev = { serverTime: null }) => {
		fetch('https://api.binance.com/api/v1/time')
			.then((res) => res.json())
			.then(push);

		return prev;
	});
}
```
