### ISSUE TITLE
value instanceof EventEmitter. Подписка в конструкторе

### ISSUE THREAD

**Issue by dwfe** [Riim/cellx#48]
Привет.

Зачем делать подписку в конструкторе, если в этот момент ячейка неактивная:
https://github.com/Riim/cellx/blob/master/src/Cell.ts#L262
?

Вроде бы некуда еще отправлять изменения...

**Comment by Riim** [comment]
Привет!

Когда нет реакций и обработчиков, в _onValueChange из полезного остаётся только строка `this._updationId = ++lastUpdationId;`.
С этим _updationId тема такая: в пассивном режиме зависимости не содержат ссылки на свои реакции и не могут сообщить им о своём изменении, ну и реакции при чтении вынуждены каждый раз перевычисляться, а то вдруг что-то в зависимостях поменялось. То есть пассивные, вычисляемые ячейки становятся чем-то вроде простых функций, но некоторую мемоизацию всё же удалось добавить и за это как раз отвечает _updationId -- при записи в любую ячейку инкрементим глобальный для всех lastUpdationId, дальше читается пассивная ячейка и проставляет в свой _updationId значение из глобального lastUpdationId. Теперь при повторном чтении этой ячейки можно сравнить _updationId и глобальный lastUpdationId (https://github.com/Riim/cellx/blob/master/src/Cell.ts#L530) и если они равны, то точно изменений нигде не было, а значит можно просто вернуть запомненное значение (если же хоть что-то где-то менялось, то lastUpdationId будет больше). Понятно, что есть куча кейсов в  которых такая мемоизация ломается, но при отсутствии ссылок вряд ли тут можно что-то заметно лучше придумать.
Теперь если вернуться к _onValueChange, то внутреннее изменение значения по сути равноценно просто записи в ячейку, оно ведь так же может повлиять на значения реакций, вот и делается подписка на него для обновления lastUpdationId.
