### ISSUE TITLE
Добавить матрешку в тест на производительность

### ISSUE THREAD

**Issue by Olegych92** [Riim/cellx#5]
Матрешка тоже позволяет создавать вычисляемые свойства https://ru.matreshka.io/#!Matreshka-linkProps Почему бы не добавить ее в тест на производительность который в описании?

**Comment by Riim** [comment]
Привет. Почему бы и нет, сделаю позже. Можете сами попробовать, там всё просто ;) .

**Comment by Riim** [comment]
Добавил матрешку и mobx. Обновил результаты для последнего хрома, судя по тому, что большинство результатов просело примерно в два раза, с js движком в хроме случилось что-то печальное :(
