### ISSUE TITLE
Не происходит асинхронная подписка на ячейку?

### ISSUE THREAD

**Issue by arvitaly** [Riim/cellx#6]
Привет, или я чего-то не понимаю в логике или это ошибка? Пытаюсь вычислить значение `x` через `a` асинхронно, значение вычисляет в первый раз, однако после этого для `x`  addChangeListener не вызывается при изменении `a`.

https://gist.github.com/arvitaly/b3335f415d14c0bdcb9fa036035ad424

**Comment by arvitaly** [comment]
Я так понял, подписка возможна только синхронная, а push чисто для вычисления.

**Comment by arvitaly** [comment]
```
    setTimeout(((a) => {
        push("calc with a " + a);
    }).bind(undefined, a()), 100)
```

Видимо, вот так логичнее.

**Comment by Riim** [comment]
Да, подписка синхронная, а `push` для асинхронного результата. Наверно, правильнее как-то так:

``` js
var x = cellx((push) => {
    setTimeout(() => {
        push("test" + a());
    }, 100)

    return "test" + a()
})
```

Так `x` и подпишется на `a` и при первом вычислении получит правильное значение, а не `undefined`.

**Comment by Riim** [comment]
Если расскажите, что это за `a` и `x` и зачем в формуле `x` таймаут и одновременно зависимость от `a`, то я может смогу что-нибудь посоветовать/подсказать.

**Comment by arvitaly** [comment]
Вот у меня есть websocket-сервис, который push'ит мне с сервера значения. И есть ячейка на клиента, которая рассчитывается из приходящего результата и другой ячейки. Т.е., и при изменении с сервера и при локальном изменении, target-cell должна пересчитываться.
Первое вычисление со второй ячейкой имеет смысл только вкупе с результатом с сервера.

```
var targetCell = cellx((push)=>{
    websocketSubscribe((result)=>{
        push(sourceCell() + result);
    })
});
```

Понятно, что можно завести отдельную ячейку без зависимостей, чисто для websocket-подписки, и суммирующую ячейку, просто я думал инкапсулировать эту часть кода внутри этой ячейки.

**Comment by Riim** [comment]
Я бы результат от websocket-а отдельной ячейкой оформил, так и читается легче и переиспользовать можно:

``` js
var sourceCell = cellx();

var websocketResult = cellx((push)=>{
    websocketSubscribe((result)=>{
        push(result);
    })
});

var targetCell = cellx(()=>{
    return sourceCell() && websocketResult() ? sourceCell() + websocketResult() : null;
});
```

**Comment by arvitaly** [comment]
Да, спасибо, у меня некоторый подсознательный диссонанс, просто, вроде как значение зависит, а подписки нет, а push он не вычисляет, а только вставляет новое значение.
Возможно, дело в том, что push находится внутри функции этой ячейки, а все, что внутри нее воспринимается, как обязанность подписаться.
Я, пожалуй, не буду загонять websocket внутрь ячейки, раз уж он все равно вынесен из target-ячейки, просто по его результатам буду обновлять значние websocketResult, а то путаницы много.

```
var sourceCell = cellx();

var websocketResult = cellx();
websocketSubscribe((result)=>{
    websocketResult(result);
})

var targetCell = cellx(()=>{
    return sourceCell() && websocketResult() ? sourceCell() + websocketResult() : null;
});
```

**Comment by Riim** [comment]
Так тоже норм))
