### ISSUE TITLE
Как организовать показ загрузчика и ошибки?

### ISSUE THREAD

**Issue by arvitaly** [Riim/cellx#7]
Как быть, если есть некий UI, который зависит от нескольких ячеек, которые заполняются асинхронно, и их первое значение не имеет смысла?
Создать отдельную ячейку isLoading и isError, в которых проверять появились ли значения во всех нужных ячейках?

**Comment by Riim** [comment]
Я так и делаю:

``` js
export default class Contacts extends EventEmitter {

    @computed metadataLoaded = function() {
        return this.locations !== void 0 && this.mediaCompanyTypes !== void 0 && this.themes !== void 0 &&
            this.tags !== void 0;
    };
}
```

Вроде работает))

**Comment by arvitaly** [comment]
А как, в таком случае, быть с обновлением? Вот мы нажали кнопку обновить, старые значения ячеек сохранились, и metadataLoaded больше никогда не будет истиной. Обнулять старые значения тоже не выйдет, они должны оставаться на экране.

**Comment by Riim** [comment]
Не уверен, что верно понял вопрос, но если речь о том, что сделавшая запрос ячейка должна сделать его снова, то для этого есть почему-то не описанный метод `pull`:

``` js
var value = cellx(push => {
    makeRequest(res => {
        push(res.data.value);
    });
});

// При первом чтении или вызове 'then' произойдёт запрос.
// 'then' дожидается первого push-а, то есть здесь ждём ответ.
value('then', () => {
    log(value()); // дальше при чтении перезапрос не происходит, отдаётся запомненное значение
    // => '1'

    value('pull', 0); // заставляем ячейку перезапросить данные
    value('then', () => {
        log(value()); // '2'
    });
});
```

> Обнулять старые значения тоже не выйдет, они должны оставаться на экране.

третий параметр для сохранения значения во время запроса:

``` js
var value = cellx((push, fail, oldValue) => {
    makeRequest(res => {
        push(res.data.value);
    });

    return oldValue; // на время запроса ячейка останется со старым значением
});
```

если же нужно и значение ячейки на время запроса сохранять и как-то отмечать состояние загрузки, то тут без ещё одной ячейки не обойтись. Можно положить её рядом, но интересней как-то так:

``` js
var value = cellx(push => {
    makeRequest(res => {
        push(res.data.value);
    });
});

var displayedValue = cellx((push, fail, oldValue) => {
    return value() === void 0 ? oldValue || '' : value();
});

var currentlyLoading = cellx(() => {
    return value() === void 0;
});
```

тут `value` будет переключаться на undefined во время запроса, а `displayedValue` после первого нормального результата будет сохранять его до следующего (да и до первого норм результата, пока oldValue равен undefined, подставиться пустая строка, чтобы undefined не торчал в интерфейсе).

**Comment by arvitaly** [comment]
Все верно, но если ячеек много, а loader зависит ото всех, создавать для каждой display-ячейку?
В случае с `then`, возможно, хочется чего-то вроде Promise.all или как-то по другому работать с коллекцией, не знаю, еще надо осознать парадигму)

**Comment by Riim** [comment]
> Все верно, но если ячеек много, а loader зависит ото всех, создавать для каждой display-ячейку?

попробуйте пока так делать, если таких ячеек будет действительно много (то есть ситуация будет не в каком-то одном месте приложения) и это будет напрягать, напишите, я к тому времени хорошенько обдумаю как можно допилить cellx без ущерба производительности (есть хороший вариант).

> В случае с then, возможно, хочется чего-то вроде Promise.all

вызов функции cellx создаёт экземпляр `cellx.Cell` (там сложнее, но для простоты можно и так объяснить) и возвращает функцию которая проксирует часть своих вызовов на его (`cellx.Cell`) методы. Вызов `prop('unwrap', 0)` не проксируется на какой-то метод, он вернёт сам экземпляр `cellx.Cell`, у которого нормальные методы `then` и `catch`, то есть он совместим с обычными промисами:

``` js
Promise.all(
    somePromise,
    prop('unwrap', 0)
);
```

**Comment by Riim** [comment]
v1.6.46
Добавил метод `Cell#isPending()`, при вызове его в формуле произойдёт создание скрытой подячейки (на ячейке у которой был вызван метод) и сразу подписка на неё. Вроде это то, что нужно, и вроде даже хорошо работает. Пока это эксперементальная возможность, если будет хорошо работать, можно будет оставить. В общем, попробуйте.

Пример:

``` js
var value = cellx((push, fail, oldValue) => {
    makeRequest(res => {
        push(res.data.value);
    });

    return oldValue; // оставляем предыдущее значение на время повторных запросов
});

var currentlyLoading = cellx(() => {
    // состояние загрузки определяем подписываясь на автоматически создаваемые подячейки
    return value('isPending', 0) || otherValue('isPending', 0);
});
```

**Comment by zerkalica** [comment]
isPending просачивается через computable?

``` js

var value1 = cellx((push, fail, oldValue) => {
    makeRequest1(res => {
        push(res.data.value);
    });

    return oldValue;
});

var value2 = cellx((push, fail, oldValue) => {
    makeRequest2(res => {
        push(res.data.value);
    });

    return oldValue;
});

var computed = cellx(() => value1() + value2())

computed.isPending() === true ?

```

**Comment by Riim** [comment]
Нет((.
