### ISSUE TITLE
Синтаксис вызова методов

### ISSUE THREAD

**Issue by arvitaly** [Riim/cellx#8]
Кстати, а какова причина такого синтаксиса вызова метода? Почему не через точку?

```
var targetCell = cellx();
targetCell.subscribe(()=>{

})
```

Тогда и 0 не придется писать для non-arguments методов?

**Comment by Riim** [comment]
1) Нет проблем с контекстом когда ячейка используется как свойство:

``` js
// prop запуститься в контексте this и он (this) подставиться как контекст обработчика
this.prop('subscribe', function() {});

// subscribe запуститься в контексте prop, а он как контекст обработчику нафик не нужен,
// нужно каждый раз прокидывать контекст вторым параметром,
// это часто случайно забывается
this.prop.subscribe(function() {}, this);
```

Arrow-функции проблему не решают, так как обработчик почти всегда подставляется из экземпляра:

``` js
this.prop('subscribe', this._onPropChange);
```

Лежать на экземпляре он должен для возможности переопределения в дочерних классах.

2) Всякие оптимизационные моменты, ячейка -- это функция, в неё свой прототип не подставишь, приходится переписывать на неё кучу методов, тут, во-первых, замедление от самого переписывания и довольно значительное, во-вторых, сотни-тысячи ячеек в приложении помноженные на десятки методов -- это десятки-сотни тысяч ссылок и как следствие большее потребление памяти, хотя единичная ссылка в js конечно очень легковесна.

Это решение принималось очень давно и там плюсов и минусов было довольно много, я сейчас только основные помню. Плюсы были больше технические, вроде тех, что выше, а минусы в основном из серии "не хочется пугать пользователя чем-то необычным". Ещё серьёзным минусом было то, что появление typescript-а уже тогда было предсказуемым и я считал, что будут проблемы с автодополнением в редакторе, но сегодняшний typescript без проблем позволяет это описать и получить нормальное автодополнение, как-то так вроде:

``` js
cellx(methodName: 'subscribe', listener: Function)
cellx(methodName: 'then', onFulfilled: Function, onRejected?: Function)
```

то есть вместо типа указывается значение и эти значения автодополняются с дальнейшей проверкой компилятором остальной сигнатуры вызова. В общем, этот минус сам собой отпал.

**Comment by arvitaly** [comment]
Автодополнения вроде нет в таком случае, есть только подсказка к сигнатуре (всплывающее окно, вместо подстановки). А лично меня смутил нолик, ну и аргументацию было интересно услышать.

А сделать ячейку не функцией, я так понимаю, не позволяет желание сохранить этот синтаксис? Т.е. можно было бы сделать и get, set методы.

```
var x = cellx();
x.set("new value");
x.get();
```

**Comment by Riim** [comment]
> Автодополнения вроде нет в таком случае, есть только подсказка к сигнатуре (всплывающее окно, вместо подстановки)

да, точно, тут, наверно, ценнее даже не дополнение, а чтобы компилятор всё это нормально мог проверять.

> А сделать ячейку не функцией

в соседнем ишъю как раз немного рассказал про устройство функции cellx:

> вызов функции cellx создаёт экземпляр `cellx.Cell` (там сложнее, но для простоты можно и так объяснить) и возвращает функцию которая проксирует часть своих вызовов на его (`cellx.Cell`) методы

то есть можно использовать сам класс ячейки:

``` js
let x = new cellx.Cell(5);
x.get();
x.subscribe(function() {});
```

**Comment by arvitaly** [comment]
Ага, ну тогда вопрос закрыт, спасибо.
