### ISSUE TITLE
Как добавить метод в прототип?

### ISSUE THREAD

**Issue by arvitaly** [Riim/cellx#9]
Экспериментирую с возможностями cellx https://gist.github.com/arvitaly/8ae581f94650d5a9369f91421641cdfa

А есть возможность сделать то же самое, но для cellx-функции, а не для cellx.Cell, т.е. для того самого упрощенного синтаксиса добавить свой метод?

**Comment by arvitaly** [comment]
И добавочный вопрос, а как узнать, что это вообще ячейка, если она передается, как параметр?
Аналог `cell instanceof cellx.Cell`?

**Comment by Riim** [comment]
Проксируются на прототип все методы кроме `bind` и `unwrap` ([код](https://github.com/Riim/cellx/blob/master/src/cellx.js#L86)), то есть метод добавленный в прототип сразу доступен и для упрощённого синтаксиса.

> Аналог cell instanceof cellx.Cell?

``` js
x.constructor == cellx.Cell
```

Пока так, позже `Symbol.hasInstance` появится (им можно будет переопределять поведение instanceof). Тут babel вроде не поможет, надо ждать нативной реализации.

UPD: хотя надо попробовать, typeof для 'symbol' сделали же, пусть и с ограничениями.

**Comment by Riim** [comment]
Малость ошибся, вот так правильно:

``` js
x.constructor == cellx
```

**Comment by arvitaly** [comment]
Ага, спасибо
